# Generated by Django 4.1 on 2022-08-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jbv', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=38)),
                ('party_id', models.CharField(max_length=38)),
                ('message', models.CharField(max_length=280)),
                ('time_sent', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_id', models.CharField(max_length=38, primary_key=True, serialize=False)),
                ('jbv', models.CharField(max_length=8)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=38, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=75)),
                ('party_id', models.CharField(max_length=38)),
            ],
        ),
    ]
