# Generated by Django 4.1 on 2022-08-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.RemoveField(
            model_name='party',
            name='jbv',
        ),
        migrations.AddField(
            model_name='party',
            name='video_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
